### ISSUE TITLE
Data to reproduce results

### ISSUE THREAD

**Issue by shumailaahmed** [VideoNetworks/TokShift-Transformer#1]
Can you share the data subset of kinetics400 to reproduce the results, TIA.

**Comment by hzhang57** [comment]
The total set of Kinetics400 zip is at 100gb scale, currently, we have not find a drive link to host the dataset.

**Comment by hzhang57** [comment]
A suggestion is to use https://github.com/cvdfoundation/kinetics-dataset to download kinetic400. They host the original resolution data (k400 should around 200GB more). We use a resized k400 version (short side to 331), our data is at 100 GB scale.
