### ISSUE TITLE
single server multi gpu option

### ISSUE THREAD

**Issue by ibrahimrazu** [VideoNetworks/TokShift-Transformer#2]
Hi, 
Thanks a lot for sharing your code. I had a little concern. Have you tested your pipeline with single server multi-gpu?

Thanks

**Comment by VideoNetworks** [comment]
Hi, I trained the most models with a V100 machine with 2GPUs, except the largest model (a v100 with 8 GPUs).

**Comment by ibrahimrazu** [comment]
thanks a lot. i'll try that
