### ISSUE TITLE
About fine-tune on small-scale datasets

### ISSUE THREAD

**Issue by sha310139** [VideoNetworks/TokShift-Transformer#3]
Hi,

Thanks for sharing this amazing work.
I'm interested in how to fine-tune on small-scale datasets.
Can you share fine-tuning commands and config files? It will be very helpful for me.

Thanks.

**Comment by VideoNetworks** [comment]
Training command and config is similar to train k400. 

cmd = "python -u main_ddp_shift_egaze.py \
		--multiprocessing-distributed --world-size 1 --rank 0 \
		--dist-ur tcp://127.0.0.1:23677 \
		--name k400 \
                -resume2 path-to-k400-weights \
		--cfg ./config/custom/egaze/egaze_vit_config_D_TK_8x8_Div4.yml"
os.system(cmd)

For main_ddp_shift_egaze.py, an extra resum2 is insert before resume args.

![Screenshot from 2022-01-24 16-49-53](https://user-images.githubusercontent.com/82623705/150750716-5d7eb4f3-3b81-4a83-99cd-0dae97862da9.png)

**Comment by sha310139** [comment]
Thanks for your reply !
I will try to modify and train it.
