### ISSUE TITLE
train log

### ISSUE THREAD

**Issue by lyhZz** [VideoNetworks/TokShift-Transformer#4]
Hello, I am very interested in your work, can you provide the training log of the model on k400, ucf-101, thank you

**Comment by VideoNetworks** [comment]
Hi，I upload training log for Kinetics-400 online, we use 3 views evaluation (instead of 30 views) during validation for time-saving.
https://tensorboard.dev/experiment/rd7mhBgUQZegnmszyL2Y6A/#scalars&_smoothingWeight=0

**Comment by lyhZz** [comment]
> Hi，I upload training log for Kinetics-400 online, we use 3 views evaluation (instead of 30 views) during validation for time-saving. https://tensorboard.dev/experiment/rd7mhBgUQZegnmszyL2Y6A/#scalars&_smoothingWeight=0

Thank you!
